[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
extra_scripts = pre:scripts/ensure_secrets.py
lib_deps =
    adafruit/DHT sensor library@^1.4.3
    adafruit/Adafruit Unified Sensor@^1.1.5
    bblanchon/ArduinoJson@^7.2.0
